#!/usr/bin/env python3
"""Refresh the GitHub snapshot shown on dooubletap.github.io.

The site never calls the GitHub API from the visitor's browser (see /privacy/).
Instead this script takes a snapshot of the public profile and repositories and
writes it to assets/github-data.js, which the page reads like any other file.

    python tools/update-github.py
    GITHUB_TOKEN=ghp_xxx python tools/update-github.py    # optional, higher rate limit

Standard library only. Without a token GitHub allows 60 requests an hour, which
is enough for one run (profile + repo pages + per-repo languages for own repos).
If the limit is hit, the script falls back to each repo's primary language.
"""
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

USER = "DooubleTap"
API = "https://api.github.com"
OUT = Path(__file__).resolve().parent.parent / "assets" / "github-data.js"


def get(url):
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "dooubletap.github.io snapshot",
    })
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main():
    user = get(f"{API}/users/{USER}")
    repos, page = [], 1
    while True:
        batch = get(f"{API}/users/{USER}/repos?per_page=100&page={page}&sort=pushed")
        repos += batch
        if len(batch) < 100:
            break
        page += 1

    langs_ok = True
    out_repos = []
    for r in repos:
        item = {
            "name": r["name"],
            "desc": r["description"] or "",
            "lang": r["language"],
            "stars": r["stargazers_count"],
            "fork": r["fork"],
            "created": r["created_at"][:10],
            "pushed": r["pushed_at"][:10],
            "url": r["html_url"],
            "home": r["homepage"] or "",
            "topics": r.get("topics", []),
        }
        # Byte counts per language, own repos only (forks are other people's code).
        if not r["fork"] and langs_ok:
            try:
                item["langs"] = get(r["languages_url"])
            except urllib.error.HTTPError as e:
                if e.code in (403, 429):
                    print("Rate limit reached: using primary languages only.", file=sys.stderr)
                    langs_ok = False
                else:
                    raise
        out_repos.append(item)

    data = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "user": {
            "login": user["login"],
            "name": user["name"],
            "location": user["location"],
            "public_repos": user["public_repos"],
            "followers": user["followers"],
            "following": user["following"],
            "created": user["created_at"][:10],
            "url": user["html_url"],
        },
        "repos": out_repos,
    }
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "/* Generated by tools/update-github.py — do not edit by hand. */\n"
        f"window.GH_DATA={body};\n",
        encoding="utf-8",
    )
    own = sum(1 for r in out_repos if not r["fork"])
    print(f"Wrote {OUT.name}: {len(out_repos)} repos ({own} own), snapshot {data['generated']}")


if __name__ == "__main__":
    main()
